import lsblg from "../../../../public/Img/Catalog/Chillers/lsblg.png";
import scafhv from "../../../../public/Img/Catalog/Chillers/scaf-hv.png";

export const chillers = [
   {
      name: "Высокопроизводительные винтовые чиллеры LSBLG",
      url: "lsblg",
      imges: [lsblg],
      description:
         "Серия чиллеров Midea LSBLG представляет собой высокоэффективные воздушно-охлаждаемые винтовые чиллеры, разработанные для соответствия современным и будущим требованиям в области надежности, энергоэффективности и интеллектуального управления. Эти чиллеры оснащены двумя винтовыми компрессорами с переменной емкостью, которые идеально сочетаются с охладителями и конденсаторами, оптимально настроенными для обеспечения высокой теплопередачи и эффективности устройства.",
      company: "Midea",
      compressor: "Bitzer",
      freonType: "R134a",
      connectType: "Victaulic",
      heatExchanger: "Кожухо-трубный теплообменник",
      controlType: "EXV",
      oilType: "BSE170",
      chillerModel: [
         {
            model: "LSBLGWXXX/C 380",
            coolingPower: "376",
            coolingEnergyConsumption: "124",
            coolingCop: "3.03",
            iplv: "4.09",
            compressorQuantity: "1",
            fanQuantity: "6",
            airFlow: "23000×6",
            freonQuantity: "76",
            waterVol: "65.4",
            size: "2280/2400/3810",
            weight: "3920",
         },
         {
            model: "LSBLGWXXX/C 500",
            coolingPower: "496",
            coolingEnergyConsumption: "159",
            coolingCop: "3.11",
            iplv: "4.2",
            compressorQuantity: "1",
            fanQuantity: "8",
            airFlow: "23000×8",
            freonQuantity: "90",
            waterVol: "86",
            size: "2280/2400/4865",
            weight: "4420",
         },
         {
            model: "LSBLGWXXX/C 600",
            coolingPower: "594",
            coolingEnergyConsumption: "187",
            coolingCop: "3.17",
            iplv: "4.29",
            compressorQuantity: "1",
            fanQuantity: "10",
            airFlow: "23000×10",
            freonQuantity: "105",
            waterVol: "103.2",
            size: "2280/2400/5800",
            weight: "5160",
         },
         {
            model: "LSBLGWXXX/C 720",
            coolingPower: "720",
            coolingEnergyConsumption: "234",
            coolingCop: "3.07",
            iplv: "4.17",
            compressorQuantity: "1",
            fanQuantity: "10",
            airFlow: "23000×10",
            freonQuantity: "140",
            waterVol: "123.8",
            size: "2280/2400/5800",
            weight: "5750",
         },
         {
            model: "LSBLGWXXX/C 900",
            coolingPower: "902",
            coolingEnergyConsumption: "285",
            coolingCop: "3.16",
            iplv: "4.27",
            compressorQuantity: "2",
            fanQuantity: "14",
            airFlow: "23000×14",
            freonQuantity: "76+90",
            waterVol: "154.8",
            size: "2280/2400/8800",
            weight: "8050",
         },
         {
            model: "LSBLGWXXX/C 1000",
            coolingPower: "996",
            coolingEnergyConsumption: "318",
            coolingCop: "3.13",
            iplv: "4.25",
            compressorQuantity: "2",
            fanQuantity: "16",
            airFlow: "23000×16",
            freonQuantity: "90x2",
            waterVol: "172",
            size: "2280/2400/9640",
            weight: "8410",
         },
         {
            model: "LSBLGWXXX/C 1200",
            coolingPower: "1203",
            coolingEnergyConsumption: "381",
            coolingCop: "3.15",
            iplv: "4.29",
            compressorQuantity: "2",
            fanQuantity: "16",
            airFlow: "23000×16",
            freonQuantity: "105x2",
            waterVol: "206.4",
            size: "2280/2400/9640",
            weight: "9210",
         },
         {
            model: "LSBLGWXXX/C 1420",
            coolingPower: "1419",
            coolingEnergyConsumption: "466",
            coolingCop: "3.04",
            iplv: "4.15",
            compressorQuantity: "2",
            fanQuantity: "20",
            airFlow: "23000×20",
            freonQuantity: "140x2",
            waterVol: "244.2",
            size: "2280/2400/11700",
            weight: "10730",
         },
      ],
   },
   {
      name: "Модульный чиллер серии Inverter Screw",
      url: "inverter-screw",
      imges: [scafhv],
      description:
         "Серия инверторных винтовых чиллеров Midea AirBoost представляет собой продукты, сочетающие в себе новейшие инженерные разработки и высокую энергоэффективность",
      company: "Midea",
      compressor: "Полугерметичный двухроторный винтовой компрессор",
      freonType: "R134a",
      connect: "380V-3Ph-50Hz",
      heatExchanger: "Кожухо-трубный теплообменник",
      chillerModel: [
         {
            model: "SCAF HV 115",
            coolingPower: "397.1",
            coolingEnergyConsumption: "116.5",
            coolingCop: "3.41",
            iplv: "4.91",
            compressorQuantity: "1",
            fanQuantity: "6",
            freonQuantity: "126",
            maxPowerStart: "192.4",
            waterVol: "68.3",
            size: "2300/2460/4440",
            weight: "4240",
         },
         {
            model: "SCAF HV 140",
            coolingPower: "500.6",
            coolingEnergyConsumption: "145.9",
            coolingCop: "3.43",
            iplv: "4.98",
            compressorQuantity: "1",
            fanQuantity: "8",
            freonQuantity: "148",
            maxPowerStart: "238.8",
            waterVol: "86.1",
            size: "2300/2460/5240",
            weight: "4950",
         },
         {
            model: "SCAF HV 175",
            coolingPower: "618.1",
            coolingEnergyConsumption: "181.3",
            coolingCop: "3.41",
            iplv: "5.03",
            compressorQuantity: "1",
            fanQuantity: "10",
            airFlow: "106.3",
            freonQuantity: "168",
            maxPowerStart: "302.7",
            waterVol: "106.3",
            size: "2300/2460/6245",
            weight: "5500",
         },
         {
            model: "SCAF HV 205",
            coolingPower: "723.8",
            coolingEnergyConsumption: "212.3",
            coolingCop: "3.41",
            iplv: "5.02",
            compressorQuantity: "1",
            fanQuantity: "12",
            freonQuantity: "192",
            maxPowerStart: "350.7",
            waterVol: "124.5",
            size: "2300/2460/7250",
            weight: "6170",
         },
         {
            model: "SCAF HV 240",
            coolingPower: "838.4",
            coolingEnergyConsumption: "245.9",
            coolingCop: "3.41",
            iplv: "5.03",
            compressorQuantity: "1",
            fanQuantity: "14",
            freonQuantity: "225",
            maxPowerStart: "414.5",
            waterVol: "144.2",
            size: "2300/2460/8255",
            weight: "7050",
         },
         {
            model: "SCAF HV 275",
            coolingPower: "965.6",
            coolingEnergyConsumption: "284",
            coolingCop: "3.4",
            iplv: "5.01",
            compressorQuantity: "1",
            fanQuantity: "16",
            freonQuantity: "280",
            maxPowerStart: "474.2",
            waterVol: "166.1",
            size: "2300/2460/9260",
            weight: "7620",
         },
         {
            model: "SCAF HV 330",
            coolingPower: "1158.1",
            coolingEnergyConsumption: "339.6",
            coolingCop: "3.41",
            iplv: "4.93",
            compressorQuantity: "2",
            fanQuantity: "18",
            freonQuantity: "2x168",
            maxPowerStart: "565.3",
            waterVol: "199.2",
            size: "2300/2460/10265",
            weight: "9800",
         },
         {
            model: "SCAF HV 385",
            coolingPower: "1367.6",
            coolingEnergyConsumption: "402.2",
            coolingCop: "3.4",
            iplv: "5.03",
            compressorQuantity: "2",
            fanQuantity: "20",
            freonQuantity: "2x185",
            maxPowerStart: "668.4",
            waterVol: "235.2",
            size: "2300/2460/11270",
            weight: "10940",
         },
         {
            model: "SCAF HV 410",
            coolingPower: "1448.4",
            coolingEnergyConsumption: "426",
            coolingCop: "3.4",
            iplv: "5.01",
            compressorQuantity: "2",
            fanQuantity: "20",
            freonQuantity: "2x200",
            maxPowerStart: "720.4",
            waterVol: "249.1",
            size: "2300/2460/11270",
            weight: "10980",
         },
      ],
   },
   {
      name: "Компактные чиллеры серии Aqua Mini",
      url: "aqua-mini",
      imges: [lsblg],
      description:
         "Девять моделей с мощностью охлаждения от 5 кВт до 18 кВт и мощностью нагрева от 5,5 кВт до 18,5 кВт. Несколько вариантов питания. Свободно сочетается с фанкойлами и напольными катушками. Владельцы дома могут выбрать лучшие типы в соответствии с их дизайнерским вкусом (для интерьера) или функциональными потребностями.",
      company: "Midea",
      compressor: "Rotary",
      freonType: "R410A",
      connect: "220/240/1/50",
      heatExchanger: "Fin-coil",
      fanType: "DC Motor",
      chillerModel: [
         {
            model: "MGC-V5W/D2N1",
            coolingPower: "5",
            coolingEnergyConsumption: "1.55",
            coolingCop: "3.23",
            heatingPower: "6.2",
            heatingEnergyConsumption: "1.9",
            heatingCop: "3.26",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "3200",
            freonQuantity: "2.5",
            maxPowerStart: "14.6",
            waterVol: "0.86",
            noiseLevel: "63",
            size: "1008x963x396",
            weight: "81",
         },
         {
            model: "MGC-V7W/D2N1",
            coolingPower: "7",
            coolingEnergyConsumption: "2.25",
            coolingCop: "3.11",
            heatingPower: "8",
            heatingEnergyConsumption: "2.5",
            heatingCop: "3.2",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "3750",
            freonQuantity: "2.5",
            maxPowerStart: "15.6",
            waterVol: "1.2",
            noiseLevel: "66",
            size: "1008x963x396",
            weight: "81",
         },
         {
            model: "MGC-V10W/D2N1",
            coolingPower: "10",
            coolingEnergyConsumption: "2.95",
            coolingCop: "3.39",
            heatingPower: "11",
            heatingEnergyConsumption: "3.14",
            heatingCop: "3.5",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "4800",
            freonQuantity: "2.8",
            maxPowerStart: "25",
            waterVol: "1.72",
            noiseLevel: "68",
            size: "970x1327x400",
            weight: "110",
         },
         {
            model: "MGC-V12W/D2N1",
            coolingPower: "11.2",
            coolingEnergyConsumption: "3.5",
            coolingCop: "3.2",
            heatingPower: "12.3",
            heatingEnergyConsumption: "3.78",
            heatingCop: "3.25",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "4800",
            freonQuantity: "2.8",
            maxPowerStart: "26",
            waterVol: "1.93",
            noiseLevel: "68",
            size: "970x1327x400",
            weight: "110",
         },
         {
            model: "MGC-V12W/D2RN1",
            coolingPower: "11.2",
            coolingEnergyConsumption: "3.38",
            coolingCop: "3.31",
            heatingPower: "12.3",
            heatingEnergyConsumption: "3.72",
            heatingCop: "3.31",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "4800",
            freonQuantity: "2.8",
            maxPowerStart: "8.9",
            waterVol: "1.92",
            noiseLevel: "68",
            size: "970x1327x400",
            weight: "110",
         },
         {
            model: "MGC-V14W/D2RN1",
            coolingPower: "12.5",
            coolingEnergyConsumption: "3.9",
            coolingCop: "3.2",
            heatingPower: "13.8",
            heatingEnergyConsumption: "4.25",
            heatingCop: "3.25",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "4800",
            freonQuantity: "2.9",
            maxPowerStart: "9.6",
            waterVol: "2.15",
            noiseLevel: "70",
            size: "970x1327x400",
            weight: "111",
         },
         {
            model: "MGC-V16W/D2RN1",
            coolingPower: "14.5",
            coolingEnergyConsumption: "4.7",
            coolingCop: "3.1",
            heatingPower: "16",
            heatingEnergyConsumption: "4.85",
            heatingCop: "3.3",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "6200",
            freonQuantity: "3.2",
            maxPowerStart: "10.1",
            waterVol: "2.49",
            noiseLevel: "72",
            size: "970x1327x400",
            weight: "111",
         },
         {
            model: "MGC-V10W/D2VN1",
            coolingPower: "10.5",
            coolingEnergyConsumption: "3.11",
            coolingCop: "3.38",
            heatingPower: "11.1",
            heatingEnergyConsumption: "3.14",
            heatingCop: "3.54",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "4120(7000)",
            freonQuantity: "6.2/2.8",
            maxPowerStart: "25",
            waterVol: "1.06(1.81)",
            noiseLevel: "56",
            size: "970x1327x400",
            weight: "110",
         },
         {
            model: "MGC-V18W/D2VN1",
            coolingPower: "17",
            coolingEnergyConsumption: "5.6",
            coolingCop: "3.04",
            heatingPower: "18.5",
            heatingEnergyConsumption: "5.78",
            heatingCop: "3.2",
            compressorQuantity: "1",
            fanQuantity: "2",
            airFlow: "4120(7000)",
            freonQuantity: "7.5/3.4",
            maxPowerStart: "30",
            waterVol: "1.72(2.92)",
            noiseLevel: "60",
            size: "970x1327x400",
            weight: "112",
         },
      ],
   },
   {
      name: "Модульные чиллеры серии Aqua Tempo Power",
      url: "aqua-tempo-power",
      imges: [lsblg],
      description:
         "Модульные чиллеры серии Aqua Tempo Power представляют собой гибкую и эффективную систему охлаждения. Эта зарекомендовавшая себя серия позволяет подбирать нужную производительность, создавая соответствующую комбинацию. Такая модульная конструкция обеспечивает высокую эффективность, даже при частичной загрузке, и снижает расходы на транспортировку и монтаж. Спиральные компрессоры, использованные в чиллерах Midea, гарантируют надежность и эффективность. V-образный теплообменник конденсатора и плавное регулированиепроизводительности спиральных компрессоров делают их высокоэффективными.",
      company: "Midea",
      compressor: "Fixed Scroll",
      freonType: "R410A",
      connect: "380-415/3/50",
      heatExchanger: "Shell-tube",
      chillerModel: [
         {
            model: "MGBL-F200W/RN1",
            coolingPower: "185",
            coolingEnergyConsumption: "63",
            coolingCop: "2.93",
            heatingPower: "200",
            heatingEnergyConsumption: "61",
            heatingCop: "3.27",
            compressorQuantity: "6",
            fanQuantity: "6",
            airFlow: "72000",
            freonQuantity: "42",
            maxPowerStart: "150",
            waterVol: "31.8",
            noiseLevel: "74",
            size: "2,850×2,110×2,000",
            weight: "1730",
         },
      ],
   },
   {
      name: "Модульные чиллеры серии Aqua Thermal",
      url: "aqua-thermal",
      imges: [lsblg],
      description:
         "Инверторные модульные чиллеры серии Aqua Thermal от Midea представляют собой универсальное оборудование для систем холодо - и теплоснабжения. Они оборудованы спиральными DC-inverter компрессорами, что позволяет значительно снизить энергопотребление и избежать высоких пусковых токов, характерных для традиционных систем.",
      company: "Midea",
      compressor: "Спираль",
      freonType: "R32",
      connect: "380-415/3/50",
      heatExchanger: "Оребренная трубка",
      fanType: "Двигатель постоянного тока",
      chillerModel: [
         {
            model: "MC-SU75-RN8L-B",
            coolingPower: "70",
            coolingEnergyConsumption: "26.8",
            coolingCop: "2.61",
            heatingPower: "75",
            heatingEnergyConsumption: "23.7",
            heatingCop: "3.16",
            compressorQuantity: "1",
            fanQuantity: "2",
            freonQuantity: "9",
            noiseLevel: "86",
            size: "2000×1770×960",
            weight: "440",
         },
         {
            model: "MC-SU90-RN8L-B",
            coolingPower: "82",
            coolingEnergyConsumption: "27.8",
            coolingCop: "2.95",
            heatingPower: "90",
            heatingEnergyConsumption: "28.1",
            heatingCop: "3.2",
            compressorQuantity: "2",
            fanQuantity: "2",
            freonQuantity: "16",
            noiseLevel: "83",
            size: "2200×2315×1135",
            weight: "635",
         },
         {
            model: "MC-SU140-RN8L-B",
            coolingPower: "130",
            coolingEnergyConsumption: "50.5",
            coolingCop: "2.57",
            heatingPower: "138",
            heatingEnergyConsumption: "44.5",
            heatingCop: "3.1",
            compressorQuantity: "2",
            fanQuantity: "2",
            freonQuantity: "15.5",
            noiseLevel: "92",
            size: "2220×2300×1135",
            weight: "670",
         },
         {
            model: "MC-SU180-RN8L-B",
            coolingPower: "164",
            coolingEnergyConsumption: "56",
            coolingCop: "2.93",
            heatingPower: "180",
            heatingEnergyConsumption: "57",
            heatingCop: "3.16",
            compressorQuantity: "4",
            fanQuantity: "4",
            freonQuantity: "32",
            noiseLevel: "92",
            size: "2752×2413×2220",
            weight: "1400",
         },
      ],
   },
   {
      name: "Чиллеры серии Aqua Tempo Super",
      url: "aqua-tempo-super",
      image: [],
      description:
         "Серия модульных чиллеров Aqua Tempo Super от Midea, включая модели MC-SS35-RN1L- B и\n" +
         "MC-SS65/RN1L, представляет собой передовое решение для систем кондиционирования.\n" +
         "Эти устройства оснащены эффективными компрессорами Danfoss и инновационным\n" +
         'кожухотрубным испарителем, который исключает "мертвые" зоны и улучшает теплообмен.\n' +
         "Серия также характеризуется наличием электронного расширительного вентиля и\n" +
         "уникального H-образного конденсатора, который увеличивает площадь воздухообмена.\n" +
         "Кроме того, чиллеры можно объединять в модули до 16 устройств, создавая мощную систему\n" +
         "с холодопроизводительностью до 2080 кВт. Эти функции обеспечивают высокую\n" +
         "энергоэффективность и гибкость в применении, делая Aqua Tempo Super идеальным выбором\n" +
         "для современных систем кондиционирования.\n" +
         "Диапазон производительности моделей варьируется от 35 до 130 кВт.",
      company: "Midea",
      connect: "380-415/3/50",
      compressor: "Fixed Scroll",
      fanType: "AC Motor",
      freonType: "R410A",
      chillerModel: [
         {
            model: "MC-SS35-RN1L-B",
            coolingPower: "35",
            coolingEnergyConsumption: "11.5",
            coolingCop: "3.04",
            heatingPower: "37",
            heatingEnergyConsumption: "11.3",
            heatingCop: "3.27",
            compressorQuantity: "1",
            fanQuantity: "1",
            freonQuantity: "6",
            noiseLevel: "65",
            size: "1,020×1,770×980",
            weight: "300",
         },
         {
            model: "MC-SS65/RN1L",
            coolingPower: "65",
            coolingEnergyConsumption: "20.4",
            coolingCop: "3.19",
            heatingPower: "69",
            heatingEnergyConsumption: "21.5",
            heatingCop: "3.21",
            compressorQuantity: "1",
            fanQuantity: "2",
            freonQuantity: "10.5",
            noiseLevel: "67",
            size: "2,000×1,770×960",
            weight: "530",
         },
         {
            model: "MC-SS80/RN1L",
            coolingPower: "80",
            coolingEnergyConsumption: "25.8",
            coolingCop: "3.1",
            heatingPower: "85",
            heatingEnergyConsumption: "26.5",
            heatingCop: "3.21",
            compressorQuantity: "2",
            fanQuantity: "2",
            freonQuantity: "13",
            noiseLevel: "67",
            size: "2,000×1,770×960",
            weight: "645",
         },
         {
            model: "MC-SS130/RN1L",
            coolingPower: "130",
            coolingEnergyConsumption: "42.3",
            coolingCop: "3.07",
            heatingPower: "138",
            heatingEnergyConsumption: "43",
            heatingCop: "3.21",
            compressorQuantity: "2",
            fanQuantity: "2",
            freonQuantity: "21",
            noiseLevel: "68",
            size: "2,200×2,060×1,120",
            weight: "965",
         },
      ],
   },
   {
      name: "Высокопроизводительные чиллеры в малошумном исполнении и спиральными компрессорами",
      url: "aqua-tempo-super",
      image: [],
      description: "Серия чиллеров RHAG от Midea – это надежные и эффективные решения для охлаждения воды в промышленных и коммерческих приложениях.",
      company: "Midea",
      connect: "380V-3Ph-50Hz",
      compressor: "Hermetic scroll compressor",
      freonType: "R410A",
      chillerModel: [
         {
            model: "RHAG 100HA",
            coolingPower: "340",
            coolingEnergyConsumption: "102.5",
            coolingCop: "3.31",
            heatingPower: "335",
            heatingEnergyConsumption: "102",
            heatingCop: "3.48",
            iplv: "4.813",
            compressorQuantity: "3",
            fanQuantity: "6",
            freonQuantity: "38 + 18",
            size: "3530×2300×2500",
            weight: "2900",
         },
         {
            model: "RHAG 130HA",
            coolingPower: "460",
            coolingEnergyConsumption: "138",
            coolingCop: "3.33",
            heatingPower: "475",
            heatingEnergyConsumption: "137.5",
            heatingCop: "3.45",
            iplv: "4.72",
            compressorQuantity: "4",
            fanQuantity: "8",
            freonQuantity: "38 + 38",
            size: "4700×2300×2500",
            weight: "3870",
         },
         {
            model: "RHAG 200HA",
            coolingPower: "680",
            coolingEnergyConsumption: "205",
            coolingCop: "3.31",
            heatingPower: "710",
            heatingEnergyConsumption: "204",
            heatingCop: "3.48",
            iplv: "4.81",
            compressorQuantity: "6",
            fanQuantity: "12",
            freonQuantity: "38 + 18 + 38 + 18",
            size: "7060×2300×2500",
            weight: "5800",
         },
         {
            model: "RHAG 230HA",
            coolingPower: "800",
            coolingEnergyConsumption: "240.5",
            coolingCop: "3.32",
            heatingPower: "830",
            heatingEnergyConsumption: "239.5",
            heatingCop: "3.46",
            iplv: "4.75",
            compressorQuantity: "7",
            fanQuantity: "14",
            freonQuantity: "38 + 18 + 38 + 38",
            size: "8230×2300×2500",
            weight: "6770",
         },
         {
            model: "RHAG 260HA",
            coolingPower: "920",
            coolingEnergyConsumption: "276",
            coolingCop: "3.33",
            heatingPower: "950",
            heatingEnergyConsumption: "275",
            heatingCop: "3.45",
            iplv: "4.72",
            compressorQuantity: "8",
            fanQuantity: "16",
            freonQuantity: "38 + 38 + 38 + 38",
            size: "9400×2300×2500",
            weight: "7740",
         },
      ],
   },
   {
      name: "Водяные чиллеры серии Magboost",
      url: "magboost",
      image: [],
      description:
         "Водяные чиллеры серии Magboost от Midea - это передовое оборудование, специально разработанное для обеспечения эффективного и надежного охлаждения воды в промышленных и коммерческих системах. Чиллеры серии Magboost обладают высокой производительностью и эффективностью охлаждения воды. Они способны поддерживать стабильную и комфортную температуру в системах охлаждения даже при высоких нагрузках",
      company: "Midea",
      compressor: "Магнитный подшипник",
      chillerModel: [
         {
            model: "CCWG 170EV",
            coolingPower: "597.7",
            coolingEnergyConsumption: "93.43",
            coolingCop: "6.39",
            iplv: "10.20",
            motorPower: "150.0",
            maxPower: "167.9",
            evaporatorWaterFlow: "97.35",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "114.7",
            condenserpipeConnect: "DN150",
            size: "3500×1400×1800",
            weight: "3110",
         },
         {
            model: "CCWG 200EV",
            coolingPower: "703.2",
            coolingEnergyConsumption: "107.7",
            coolingCop: "6.53",
            iplv: "10.56",
            motorPower: "150.0",
            maxPower: "193.5",
            evaporatorWaterFlow: "108.6",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "135.1",
            condenserpipeConnect: "DN150",
            size: "3500×1400×1800",
            weight: "3110",
         },
         {
            model: "CCWG 230EV",
            coolingPower: "808.7",
            coolingEnergyConsumption: "122.3",
            coolingCop: "6.61",
            iplv: "11.11",
            motorPower: "150.0",
            maxPower: "218.9",
            evaporatorWaterFlow: "124.9",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "155.0",
            condenserpipeConnect: "DN150",
            size: "3500×1400×1800",
            weight: "3225",
         },
         {
            model: "CCWG 250EV",
            coolingPower: "879",
            coolingEnergyConsumption: "134.3",
            coolingCop: "6.54",
            iplv: "11.36",
            motorPower: "150.0",
            maxPower: "241.2",
            evaporatorWaterFlow: "135.8",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "168.8",
            condenserpipeConnect: "DN150",
            size: "3500×1400×1800",
            weight: "3225",
         },
         {
            model: "CCWG 270EV",
            coolingPower: "949.3",
            coolingEnergyConsumption: "143.7",
            coolingCop: "6.60",
            iplv: "11.79",
            motorPower: "150.0",
            maxPower: "258.3",
            evaporatorWaterFlow: "146.7",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "182.6",
            condenserpipeConnect: "DN150",
            size: "3500×1400×1800",
            weight: "3350",
         },
         {
            model: "CCWG 300EV",
            coolingPower: "1055",
            coolingEnergyConsumption: "161",
            coolingCop: "6.55",
            iplv: "10.69",
            motorPower: "280.0",
            maxPower: "289.3",
            evaporatorWaterFlow: "163",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "202.5",
            condenserpipeConnect: "DN200",
            size: "4150×1650×1850",
            weight: "4970",
         },
         {
            model: "CCWG 350EV",
            coolingPower: "1231",
            coolingEnergyConsumption: "189.8",
            coolingCop: "6.48",
            iplv: "11.24",
            motorPower: "280.0",
            maxPower: "341",
            evaporatorWaterFlow: "190.1",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "236.6",
            condenserpipeConnect: "DN200",
            size: "4150×1650×1850",
            weight: "5100",
         },
         {
            model: "CCWG 380EV",
            coolingPower: "1336",
            coolingEnergyConsumption: "203.4",
            coolingCop: "6.56",
            iplv: "11.29",
            motorPower: "280.0",
            maxPower: "365.6",
            evaporatorWaterFlow: "206.4",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "256.7",
            condenserpipeConnect: "DN200",
            size: "4150×1650×1850",
            weight: "5140",
         },
         {
            model: "CCWG 400EV",
            coolingPower: "1406",
            coolingEnergyConsumption: "216.2",
            coolingCop: "6.50",
            iplv: "11.43",
            motorPower: "280.0",
            maxPower: "388.5",
            evaporatorWaterFlow: "217.3",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "270.2",
            condenserpipeConnect: "DN200",
            size: "4150×1850×1950",
            weight: "5980",
         },
         {
            model: "CCWG 420EV",
            coolingPower: "1477",
            coolingEnergyConsumption: "227.9",
            coolingCop: "6.48",
            iplv: "11.47",
            motorPower: "280.0",
            maxPower: "409.4",
            evaporatorWaterFlow: "228.2",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "284",
            condenserpipeConnect: "DN200",
            size: "4150×1850×1950",
            weight: "6030",
         },
         {
            model: "CCWG 450EV",
            coolingPower: "1582",
            coolingEnergyConsumption: "233.6",
            coolingCop: "6.77",
            iplv: "11.35",
            motorPower: "400.0",
            maxPower: "419.8",
            evaporatorWaterFlow: "244.4",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "302.8",
            condenserpipeConnect: "DN250",
            size: "4700×2050×2450",
            weight: "7670",
         },
         {
            model: "CCWG 500EV",
            coolingPower: "1758",
            coolingEnergyConsumption: "260.3",
            coolingCop: "6.75",
            iplv: "11.66",
            motorPower: "400.0",
            maxPower: "467.8",
            evaporatorWaterFlow: "271.6",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "336.7",
            condenserpipeConnect: "DN250",
            size: "4700×2050×2450",
            weight: "7800",
         },
         {
            model: "CCWG 550EV",
            coolingPower: "1934",
            coolingEnergyConsumption: "287.2",
            coolingCop: "6.73",
            iplv: "11.99",
            motorPower: "400.0",
            maxPower: "516.1",
            evaporatorWaterFlow: "298.8",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "370.6",
            condenserpipeConnect: "DN250",
            size: "4700×2050×2450",
            weight: "7980",
         },
         {
            model: "CCWG 600EV",
            coolingPower: "2110",
            coolingEnergyConsumption: "318.7",
            coolingCop: "6.62",
            iplv: "12.01",
            motorPower: "400.0",
            maxPower: "572.7",
            evaporatorWaterFlow: "325.9",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "405.8",
            condenserpipeConnect: "DN250",
            size: "4700×2050×2450",
            weight: "8170",
         },
         {
            model: "CCWG 650EVD",
            coolingPower: "2285",
            coolingEnergyConsumption: "339.3",
            coolingCop: "6.73",
            iplv: "11.46",
            motorPower: "560.0",
            maxPower: "609.7",
            evaporatorWaterFlow: "353.1",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "438.9",
            condenserpipeConnect: "DN300",
            size: "5050×2000×2200",
            weight: "10820",
         },
         {
            model: "CCWG 700EVD",
            coolingPower: "2461",
            coolingEnergyConsumption: "370.2",
            coolingCop: "6.64",
            iplv: "11.68",
            motorPower: "560.0",
            maxPower: "665.2",
            evaporatorWaterFlow: "380.3",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "473",
            condenserpipeConnect: "DN300",
            size: "5050×2000×2200",
            weight: "12050",
         },
         {
            model: "CCWG 750EVD",
            coolingPower: "2637",
            coolingEnergyConsumption: "390.4",
            coolingCop: "6.75",
            iplv: "11.78",
            motorPower: "560.0",
            maxPower: "701.7",
            evaporatorWaterFlow: "407.4",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "506.7",
            condenserpipeConnect: "DN300",
            size: "5050×2000×2200",
            weight: "12170",
         },
         {
            model: "CCWG 800EVD",
            coolingPower: "2813",
            coolingEnergyConsumption: "421.3",
            coolingCop: "6.67",
            iplv: "11.93",
            motorPower: "560.0",
            maxPower: "757.1",
            evaporatorWaterFlow: "434.6",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "540.3",
            condenserpipeConnect: "DN300",
            size: "5050×2000×2200",
            weight: "12320",
         },
         {
            model: "CCWG 850EVD",
            coolingPower: "2989",
            coolingEnergyConsumption: "461.6",
            coolingCop: "6.47",
            iplv: "11.91",
            motorPower: "560.0",
            maxPower: "829.5",
            evaporatorWaterFlow: "461.7",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "575.2",
            condenserpipeConnect: "DN300",
            size: "5050×2000×2200",
            weight: "12430",
         },
         {
            model: "CCWG 900EVD",
            coolingPower: "3164",
            coolingEnergyConsumption: "460.7",
            coolingCop: "6.86",
            iplv: "11.81",
            motorPower: "800.0",
            maxPower: "828.0",
            evaporatorWaterFlow: "488.9",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "605.8",
            condenserpipeConnect: "DN300",
            size: "4750×2950×2650",
            weight: "11990",
         },
         {
            model: "CCWG 950EVD",
            coolingPower: "3340",
            coolingEnergyConsumption: "487.5",
            coolingCop: "6.85",
            iplv: "11.84",
            motorPower: "800.0",
            maxPower: "876.2",
            evaporatorWaterFlow: "516.1",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "639.6",
            condenserpipeConnect: "DN300",
            size: "4750×2950×2650",
            weight: "12140",
         },
         {
            model: "CCWG 1000EVD",
            coolingPower: "3516",
            coolingEnergyConsumption: "515.7",
            coolingCop: "6.81",
            iplv: "11.95",
            motorPower: "800.0",
            maxPower: "926.8",
            evaporatorWaterFlow: "543.2",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "673.7",
            condenserpipeConnect: "DN300",
            size: "4750×2950×2650",
            weight: "12300",
         },
         {
            model: "CCWG 1100EVD",
            coolingPower: "3868",
            coolingEnergyConsumption: "578.2",
            coolingCop: "6.68",
            iplv: "12.11",
            motorPower: "800.0",
            maxPower: "1039.1",
            evaporatorWaterFlow: "597.5",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "741.5",
            condenserpipeConnect: "DN300",
            size: "4750×2950×2650",
            weight: "12590",
         },
         {
            model: "CCWG 1200EVD",
            coolingPower: "4219",
            coolingEnergyConsumption: "636.6",
            coolingCop: "6.62",
            iplv: "12.08",
            motorPower: "800.0",
            maxPower: "1144",
            evaporatorWaterFlow: "651.9",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "812.7",
            condenserpipeConnect: "DN300",
            size: "4750×2950×2650",
            weight: "12890",
         },
         {
            model: "CCWG 1300EVD",
            coolingPower: "4571",
            coolingEnergyConsumption: "706.2",
            coolingCop: "6.91",
            iplv: "12.08",
            motorPower: "1200.0",
            maxPower: "1188",
            evaporatorWaterFlow: "706.2",
            evaporatorpipeConnect: "DN400",
            condenserWaterFlow: "877",
            condenserpipeConnect: "DN400",
            size: "5290×3300×3050",
            weight: "19670",
         },
         {
            model: "CCWG 1400EVD",
            coolingPower: "4922",
            coolingEnergyConsumption: "713",
            coolingCop: "6.9",
            iplv: "12.10",
            motorPower: "1200.0",
            maxPower: "1281.3",
            evaporatorWaterFlow: "760.5",
            evaporatorpipeConnect: "DN400",
            condenserWaterFlow: "943.1",
            condenserpipeConnect: "DN400",
            size: "5290×3300×3050",
            weight: "19990",
         },
         {
            model: "CCWG 1500EVD",
            coolingPower: "5274",
            coolingEnergyConsumption: "770",
            coolingCop: "6.84",
            iplv: "12.09",
            motorPower: "1200.0",
            maxPower: "1383.8",
            evaporatorWaterFlow: "814.8",
            evaporatorpipeConnect: "DN400",
            condenserWaterFlow: "1012",
            condenserpipeConnect: "DN400",
            size: "5290×3300×3050",
            weight: "20410",
         },
         {
            model: "CCWG 1600EVD",
            coolingPower: "5626",
            coolingEnergyConsumption: "832.3",
            coolingCop: "6.75",
            iplv: "12.03",
            motorPower: "1200.0",
            maxPower: "1495.8",
            evaporatorWaterFlow: "869.1",
            evaporatorpipeConnect: "DN400",
            condenserWaterFlow: "1079",
            condenserpipeConnect: "DN400",
            size: "5290×3300×3050",
            weight: "20830",
         },
         {
            model: "CCWG 1700EVD",
            coolingPower: "5977",
            coolingEnergyConsumption: "899.9",
            coolingCop: "6.64",
            iplv: "12",
            motorPower: "1200.0",
            maxPower: "1617.2",
            evaporatorWaterFlow: "923.5",
            evaporatorpipeConnect: "DN400",
            condenserWaterFlow: "1149",
            condenserpipeConnect: "DN400",
            size: "5290×3300×3050",
            weight: "21040",
         },
         {
            model: "CCWG 1800EVD",
            coolingPower: "6329",
            coolingEnergyConsumption: "945.9",
            coolingCop: "6.62",
            iplv: "12.05",
            motorPower: "1200.0",
            maxPower: "1716",
            evaporatorWaterFlow: "977.8",
            evaporatorpipeConnect: "DN400",
            condenserWaterFlow: "1223",
            condenserpipeConnect: "DN400",
            size: "5290×3300×3050",
            weight: "21360",
         },
      ],
   },
   {
      name: "Высокопроизводительные чиллеры в малошумном исполнении и спиральными компрессорами",
      url: "rhwe",
      image: [],
      description:
         "Модульные чиллеры серии RHWE представлены моделями производительностью от 155-ти до 481-го кВт. Холодильные машины оснащены спиральными компрессорами и высокоэффективными кожухотрубными теплообменниками. Прогрессивная функция запуска компрессора уменьшает пусковой ток и снижает нагрузку на электрические сети. Чиллер оборудован реле высокого и низкого давления, устройством защиты от перегрузки компрессоров, фазовым монитором, защитными датчиками температуры и устройством комплексного контроля работы, которое автоматически подает аварийный сигнал в случае сбоя в работе любого из компонентов системы.",
      company: "Midea",
      connect: "380V-3Ph-50Hz",
      compressor: "Hermetic scroll compressor",
      freonType: "R410A",
      chillerModel: [
         {
            model: "RCWE50HA(B)",
            coolingPower: "155",
            coolingEnergyConsumption: "29",
            coolingCop: "5.34",
            iplv: "6.42",
            noiseLevel: "64",
            compressorQuantity: "2",
            freonQuantity: "8.5 + 8.5",
            maxPower: "90",
            evaporatorWaterFlow: "26.66",
            evaporatorpipeConnect: "DN80",
            condenserWaterFlow: "33.33",
            condenserpipeConnect: "DN80",
            size: "1960×750×1780 / 2010×750×1800",
            weight: "900/1000",
         },
         {
            model: "RCWE75HA(B)",
            coolingPower: "242.5",
            coolingEnergyConsumption: "45",
            coolingCop: "5.38",
            iplv: "6.45",
            noiseLevel: "65",
            compressorQuantity: "2",
            freonQuantity: "16 + 16",
            maxPower: "144",
            evaporatorWaterFlow: "41.71",
            evaporatorpipeConnect: "DN80",
            condenserWaterFlow: "52.14",
            condenserpipeConnect: "DN80",
            size: "2520×750×1860 / 2540×750×2040",
            weight: "1100/1200",
         },
         {
            model: "RCWE110HA(B)",
            coolingPower: "362",
            coolingEnergyConsumption: "67.5",
            coolingCop: "5.36",
            iplv: "6.44",
            noiseLevel: "67",
            compressorQuantity: "3",
            freonQuantity: "36 + 18",
            maxPower: "216",
            evaporatorWaterFlow: "62.26",
            evaporatorpipeConnect: "DN125",
            condenserWaterFlow: "77.83",
            condenserpipeConnect: "DN125",
            size: "2490×1050×2030 / 2540×1050×2040",
            weight: "1950/2100",
         },
         {
            model: "RCWE145HA(B)",
            coolingPower: "481",
            coolingEnergyConsumption: "89.8",
            coolingCop: "5.35",
            iplv: "6.43",
            noiseLevel: "68",
            compressorQuantity: "4",
            freonQuantity: "34 + 34",
            maxPower: "288",
            evaporatorWaterFlow: "82.73",
            evaporatorpipeConnect: "DN125",
            condenserWaterFlow: "103.4",
            condenserpipeConnect: "DN125",
            size: "3080×1050×2030 / 3130×1050×2040",
            weight: "2250/2450",
         },
      ],
   },
   {
      name: "Высокопроизводительные чиллеры с водяным охлаждением конденсатора",
      url: "rhwe",
      image: [],
      description:
         "Линейка Aqua Force – это водоохлаждаемые чиллеры на базе винтовых компрессоров Bitzer (Германия). В линейке представлены модели производительностью от 336,9 до 1765 кВт. Применяются в качестве систем центрального кондиционирования, промышленных систем холодоснабжения. Чиллеры могут работать с BMS Modbus и бесплатной программой Midea MSC.",
      company: "Midea",
      connect: "380V-3Ph-50Hz",
      compressor: "Полу-герметичный винтовой компрессор Bitzer",
      freonType: "R134a",
      chillerModel: [
         {
            model: "Aqua Force 340",
            coolingPower: "336.9",
            coolingEnergyConsumption: "59.74",
            coolingCop: "5.63",
            iplv: "6.51",
            compressorQuantity: "1",
            freonQuantity: "130",
            maxPower: "154.6",
            evaporatorWaterFlow: "52.04",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "65.62",
            condenserpipeConnect: "DN150",
            size: "3550×1200×1830",
            weight: "2458",
         },
         {
            model: "Aqua Force 440",
            coolingPower: "436.1",
            coolingEnergyConsumption: "76.69",
            coolingCop: "5.68",
            iplv: "6.55",
            compressorQuantity: "1",
            freonQuantity: "145",
            maxPower: "208",
            evaporatorWaterFlow: "67.38",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "84.86",
            condenserpipeConnect: "DN150",
            size: "3550×1200×1843",
            weight: "2963",
         },
         {
            model: "Aqua Force 540",
            coolingPower: "535",
            coolingEnergyConsumption: "93.63",
            coolingCop: "5.71",
            iplv: "6.6",
            compressorQuantity: "1",
            freonQuantity: "160",
            maxPower: "235",
            evaporatorWaterFlow: "82.66",
            evaporatorpipeConnect: "DN150",
            condenserWaterFlow: "104",
            condenserpipeConnect: "DN150",
            size: "3550×1200×1843",
            weight: "3054",
         },
         {
            model: "Aqua Force 720",
            coolingPower: "713.3",
            coolingEnergyConsumption: "126.9",
            coolingCop: "5.61",
            iplv: "6.5",
            compressorQuantity: "1",
            freonQuantity: "230",
            maxPower: "301",
            evaporatorWaterFlow: "110.2",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "139",
            condenserpipeConnect: "DN200",
            size: "3580×1400×1980",
            weight: "3585",
         },
         {
            model: "Aqua Force 805",
            coolingPower: "798",
            coolingEnergyConsumption: "143.7",
            coolingCop: "5.55",
            iplv: "6.41",
            compressorQuantity: "1",
            freonQuantity: "230",
            maxPower: "369",
            evaporatorWaterFlow: "123.3",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "155.8",
            condenserpipeConnect: "DN200",
            size: "3580×1400×2030",
            weight: "3699",
         },
         {
            model: "Aqua Force 890",
            coolingPower: "882.1",
            coolingEnergyConsumption: "154.4",
            coolingCop: "5.71",
            iplv: "6.6",
            compressorQuantity: "1",
            freonQuantity: "250",
            maxPower: "362.8",
            evaporatorWaterFlow: "136.3",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "171.5",
            condenserpipeConnect: "DN200",
            size: "3580×1400×2082",
            weight: "3864",
         },
         {
            model: "Aqua Force 1055",
            coolingPower: "1046",
            coolingEnergyConsumption: "185.9",
            coolingCop: "5.62",
            iplv: "6.49",
            compressorQuantity: "1",
            freonQuantity: "360",
            maxPower: "396.8",
            evaporatorWaterFlow: "161.6",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "203.8",
            condenserpipeConnect: "DN200",
            size: "3650×1500×2535",
            weight: "5078",
         },
         {
            model: "Aqua Force 1200",
            coolingPower: "1190",
            coolingEnergyConsumption: "205.3",
            coolingCop: "5.79",
            iplv: "7.29",
            compressorQuantity: "2",
            freonQuantity: "330",
            maxPower: "235/301",
            evaporatorWaterFlow: "183.8",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "230.9",
            condenserpipeConnect: "DN200",
            size: "4650×1500×2290",
            weight: "6527",
         },
         {
            model: "Aqua Force 1300",
            coolingPower: "1289",
            coolingEnergyConsumption: "230.7",
            coolingCop: "5.58",
            iplv: "7.03",
            compressorQuantity: "2",
            freonQuantity: "330",
            maxPower: "235/301",
            evaporatorWaterFlow: "199.1",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "251.4",
            condenserpipeConnect: "DN200",
            size: "4650×1500×2290",
            weight: "6527",
         },
         {
            model: "Aqua Force 1410",
            coolingPower: "1397",
            coolingEnergyConsumption: "248.7",
            coolingCop: "5.61",
            iplv: "7.12",
            compressorQuantity: "2",
            freonQuantity: "340",
            maxPower: "301/301",
            evaporatorWaterFlow: "215.8",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "272.3",
            condenserpipeConnect: "DN200",
            size: "4650×1500×2290",
            weight: "6710",
         },
         {
            model: "Aqua Force 1620",
            coolingPower: "1607",
            coolingEnergyConsumption: "290.2",
            coolingCop: "5.53",
            iplv: "6.97",
            compressorQuantity: "2",
            freonQuantity: "400",
            maxPower: "369/369",
            evaporatorWaterFlow: "248.2",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "313.8",
            condenserpipeConnect: "DN200",
            size: "4650×1600×2390",
            weight: "7270",
         },
         {
            model: "Aqua Force 1780",
            coolingPower: "1765",
            coolingEnergyConsumption: "304.9",
            coolingCop: "5.78",
            iplv: "7.29",
            compressorQuantity: "2",
            freonQuantity: "400",
            maxPower: "362.8/362.8",
            evaporatorWaterFlow: "272.7",
            evaporatorpipeConnect: "DN200",
            condenserWaterFlow: "342.6",
            condenserpipeConnect: "DN200",
            size: "5180×1600×2390",
            weight: "7573",
         },
      ],
   },
   {
      name: "Высокопроизводительные чиллеры с центрифугальным компрессором",
      url: "ccwe",
      image: [],
      description:
         "Высокопроизводительные инверторные чиллеры от компании Midea - это линейка первоклассных чиллеров с использованием передовых технологий, благодаря которым вы сможете наслаждаться одним из самых эффективных в мире охлаждений!",
      company: "Midea",
      chillerModel: [
         {
            model: "CCWE 500E",
            coolingPower: "1758",
            coolingEnergyConsumption: "284.5",
            coolingCop: "6.17",
            iplv: "6.83",
            maxPower: "557.2",
            evaporatorWaterFlow: "271.6",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "337.3",
            condenserpipeConnect: "DN250",
            size: "5020×1800×2410",
            weight: "10400",
         },
         {
            model: "CCWE 550E",
            coolingPower: "1934",
            coolingEnergyConsumption: "311.7",
            coolingCop: "6.20",
            iplv: "6.83",
            maxPower: "611",
            evaporatorWaterFlow: "298.8",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "371",
            condenserpipeConnect: "DN250",
            size: "5020×1800×2410",
            weight: "10550",
         },
         {
            model: "CCWE 600E",
            coolingPower: "2110",
            coolingEnergyConsumption: "336",
            coolingCop: "6.27",
            iplv: "6.88",
            maxPower: "656.9",
            evaporatorWaterFlow: "325.9",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "404.2",
            condenserpipeConnect: "DN250",
            size: "5020×1800×2410",
            weight: "10700",
         },
         {
            model: "CCWE 650E",
            coolingPower: "2285",
            coolingEnergyConsumption: "363.4",
            coolingCop: "6.28",
            iplv: "6.91",
            maxPower: "706.8",
            evaporatorWaterFlow: "353.1",
            evaporatorpipeConnect: "DN250",
            condenserWaterFlow: "437.9",
            condenserpipeConnect: "DN250",
            size: "5020×1800×2410",
            weight: "10820",
         },
         {
            model: "CCWE 700E",
            coolingPower: "2461",
            coolingEnergyConsumption: "392.6",
            coolingCop: "6.26",
            iplv: "6.95",
            maxPower: "764.1",
            evaporatorWaterFlow: "380.3",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "471.8",
            condenserpipeConnect: "DN300",
            size: "5020×2100×2510",
            weight: "12260",
         },
         {
            model: "CCWE 750E",
            coolingPower: "2637",
            coolingEnergyConsumption: "418.6",
            coolingCop: "6.3",
            iplv: "7.2",
            maxPower: "816",
            evaporatorWaterFlow: "407.4",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "505.2",
            condenserpipeConnect: "DN300",
            size: "5020×2100×2510",
            weight: "12460",
         },
         {
            model: "CCWE 800E",
            coolingPower: "2813",
            coolingEnergyConsumption: "443.9",
            coolingCop: "6.33",
            iplv: "7.25",
            maxPower: "862.2",
            evaporatorWaterFlow: "434.6",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "538.8",
            condenserpipeConnect: "DN300",
            size: "5020×2100×2510",
            weight: "12580",
         },
         {
            model: "CCWE 850E",
            coolingPower: "2989",
            coolingEnergyConsumption: "470.9",
            coolingCop: "6.34",
            iplv: "7.29",
            maxPower: "922",
            evaporatorWaterFlow: "461.7",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "572.3",
            condenserpipeConnect: "DN300",
            size: "5020×2100×2510",
            weight: "12720",
         },
         {
            model: "CCWE 900E",
            coolingPower: "3164",
            coolingEnergyConsumption: "501",
            coolingCop: "6.31",
            iplv: "7.36",
            maxPower: "971.8",
            evaporatorWaterFlow: "488.9",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "606.7",
            condenserpipeConnect: "DN300",
            size: "5020×2100×2510",
            weight: "12850",
         },
         {
            model: "CCWE 950E",
            coolingPower: "3340",
            coolingEnergyConsumption: "522.8",
            coolingCop: "6.38",
            iplv: "7.14",
            maxPower: "1010.4",
            evaporatorWaterFlow: "516.1",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "639.5",
            condenserpipeConnect: "DN300",
            size: "5045×2260×2610",
            weight: "13560",
         },
         {
            model: "CCWE 1000E",
            coolingPower: "3516",
            coolingEnergyConsumption: "552",
            coolingCop: "6.36",
            iplv: "7.16",
            maxPower: "1068",
            evaporatorWaterFlow: "543.2",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "673.4",
            condenserpipeConnect: "DN300",
            size: "5045×2260×2610",
            weight: "13730",
         },
         {
            model: "CCWE 1100E",
            coolingPower: "3868",
            coolingEnergyConsumption: "608.3",
            coolingCop: "6.35",
            iplv: "7.11",
            maxPower: "1176",
            evaporatorWaterFlow: "597.5",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "741.1",
            condenserpipeConnect: "DN300",
            size: "5045×2260×2610",
            weight: "13950",
         },
         {
            model: "CCWE 1200E",
            coolingPower: "4219",
            coolingEnergyConsumption: "661.1",
            coolingCop: "6.38",
            iplv: "7.18",
            maxPower: "1280",
            evaporatorWaterFlow: "651.9",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "808.1",
            condenserpipeConnect: "DN300",
            size: "5045×2260×2610",
            weight: "14250",
         },
         {
            model: "CCWE 1300E",
            coolingPower: "4571",
            coolingEnergyConsumption: "715.1",
            coolingCop: "6.39",
            iplv: "7.18",
            maxPower: "1381",
            evaporatorWaterFlow: "706.2",
            evaporatorpipeConnect: "DN300",
            condenserWaterFlow: "875",
            condenserpipeConnect: "DN300",
            size: "5045×2260×2610",
            weight: "14250",
         },
      ],
   },
];
